name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install upx 4.2.4
        run: |
          wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz

          # --strip-components=number - Strip given number of leading components from file names before extraction.
          # and extract only ./upx-4.2.4-amd64_linux/upx file
          tar --strip-components 1 -xf upx-4.2.4-amd64_linux.tar.xz upx-4.2.4-amd64_linux/upx

          mv ./upx /usr/local/bin/upx
          rm upx-4.2.4-amd64_linux.tar.xz
          upx -V
      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: mszostok
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest

          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_GORELEASER }}

